apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-hpa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cron-hpa-role
subjects:
- kind: ServiceAccount
  name: cron-hpa-serviceaccount